# Generated by Django 3.2 on 2021-10-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
